TodoTable:
  Type: AWS::DynamoDB::Table
  Properties:
    TableName: TodoTable-dev
    BillingMode: PAY_PER_REQUEST
    AttributeDefinitions:
      - AttributeName: id
        AttributeType: S
    KeySchema:
      - AttributeName: id
        KeyType: HASH
